### ISSUE TITLE
Selected actions for "swipe right" not performing as intended

### ISSUE THREAD

**Issue by JCarring** [TheDabblingDuck/ankimote#26]
Worked well for me until update today (7/28). Now the "Good / Show" action actually functions as "Easy / Show", and the "Easy" action does nothing at all. There may be more broken ones.

**Comment by TheDabblingDuck** [comment]
Should be fixed for V1 scheduler in the latest update.

- Before the recent update, ankimote looked for the text 'good' on a button and then clicked the button. That didn't work for non-english languages, or when people were using addons like 'Button Colors' or 'Auto Ease Factor', so the new update instead directly signaled answer button 3, which is always 'good' with the V2 scheduler but can sometimes be 'easy' with the V1 scheduler.
- Has now been fixed to detect when the V1 scheduler is being used in learning/relearning mode.

Please let me know if your issue is resolved.

**Comment by homeslice2** [comment]
This addon worked perfectly previously but as of 8/3 the swipe right for me (labeled as show/good) now functions as hard (long press in settings). A fix would be greatly appreciated.  Also I just deleted the addon and redownloaded it so the update did not fix this issue
